### ISSUE TITLE
v2.0.29 new interface or internal problems

### ISSUE THREAD

**Issue by pkartsev** [maoserr/epublifier#109]
Hi, very good extension! used it earlier (2-3 weeks ago)
tried to use it today, it happened to have updated interface and now I have problems:

( Firefox, Linux, KDE Plasma. Downloading for example https://www.novelupdates.com/series/fake-saint-of-the-year/  )

1) Selecting checkboxes manually (without "All") = can not select more than 3 or 4 (looks like fast repeated mouse click is recognized as double click which deselects anything else?) 
2) No button to stop downloading if started (and percentage going over 100%) - tried clicking "X" but it clears the chapter list completely.
3) Deselecting chapters during download = the download queue continues running and doing something. (Selecting all chapters again = new chapters are downloaded, but several skipped chapters remain skipped.)
4) Now impossible to download in two batches (like in earlier version): if some chapter is skipped, no epub is possible. You need to select "All" and wait to download every chapter again. (Or maybe my impatience)
5) Clicking "Epub" during download = no reaction, but the click is remembered somewhere, and if we click "Epub" several times, after downloading completed, we get many browser windows "Save as.." which block each other and not clickable excluding the last one (if I manage to find it)

Best Regards!

**Comment by maoserr** [comment]
1,4 multi select behavior has changed. You should hold down ctrl for multiple single selection, or use shift to select a range

2, there's no way to cancel on-going download. This wasn't a feature before either, not sure how you could cancel?

3, 5 doing stuff during download will screw stuff up. Only thing I can think of is to disable the UI during download

**Comment by pkartsev** [comment]
about canceling download, I probably remember wrong. During download, I could de-select all chapters, then the progress bar would quickly reach 100%, effectively stopping the process. Probably unintended behavior :)

As of removing the checkboxes, I think it will decrease the plugin capabilities.

I was frequently blocked by server-side DOS protection, so simply did download in 3-5 chapters chunks and waited for some time to repeat with next chapters. Then re-selected the checkboxes for all downloaded chapters and exported them into epub.

Example from today: https://www.novelupdates.com/series/avoid-the-death-route/ leads to https://novelonomicon.com/category/novels/avoid-the-death-route/ with finite set of chapters (10-39).

"Parse" downloads 10-39 chapters successfully, but the percentage stops at "99.99999999999997%" and clicking "Epub" does nothing ("No file generated.")

Probably something stuck in server-side, or in downloader... either case, not in my power. But in the older version I would bypass this problem by checking only chapters 1-10 or 11-20 and getting epub for this range, incomplete, but still.

(Another possibility, to create Epub from the downloaded chapters only, if there are too many, for example only for the 1st hundred of 1000+ present)

Anyways, very useful plugin, thanks! Helps to fill the tablet for reading later without internet.

I'd try to touch the scripts myself but can't understand where to start and whether the browser would allow it :)

**Comment by maoserr** [comment]
Removing checkboxes won't remove functionality, you can still hold down ctrl to do the same thing.

The example you linked is show that website is completely down for all chapters except the last few. I'm not sure how you were able to download chapters 10-30.

anyways, since there's no bug being reported. I'm closing this issue soon.
