### ISSUE TITLE
[BUG]  We are unable to load the verification. Please unblock any scripts or login to continue reading.

### ISSUE THREAD

**Issue by neitsab** [maoserr/epublifier#122]
Hi, trying to epublify https://www.novelupdates.com/series/reincarnation-of-the-strongest-sword-god/, all chapters are shortened due to the need for verification:

![image](https://github.com/maoserr/epublifier/assets/2963014/6780d10d-77a8-42f0-b462-2cd45f3ae8b2)

However, I can't do so through the extension JS engine. How can we circumvent this issue?

**Required info:**
 - Browser: Firefox 113.0.1 (Archlinux 64 bits)
 - Extension Version: 2.0.31

Thanks!

**Comment by maoserr** [comment]
novel update just has links to other sites, every novel can be a different host. Some novels have captcha.
