### ISSUE TITLE
[BUG] "No file generated" for some novels

### ISSUE THREAD

**Issue by pkartsev** [maoserr/epublifier#136]
**Describe the bug**
"No file generated" message after clicking "Epub button" for the novel below.

All chapters are loaded and parsed OK (excluding ch.121 so I deselect it for now)

1) Clicking "Epub" button gives "No file generated".

2) Even if I select only several checkboxes for good chapters, the button is active but the file is not generated.

3) I reloaded the webpage, re-parsed only 1 to 5 chapters, Epub is not generated.

**Required info**
URL: https://woopread.com/series/the-villainess-lives-twice-novel/
(changed regex for chapter links to "C.*")

Browser: Firefox v113.0.1, Linux

Plugin version: not sure where to find, but probably the latest.

**Comment by maoserr** [comment]
Looks like missing description is prevent file generation. I'll have to add a default description.

**Comment by maoserr** [comment]
fixed
