### ISSUE TITLE
[Problem] Not loading text from inoveltranslation.com

### ISSUE THREAD

**Issue by pkartsev** [maoserr/epublifier#145]
**Describe the bug**
Not loading text from inoveltranslation.com: the parsed chapters are loaded but empty.
Though visible when opening URLs in the same browser.
Looking at the page source, the text is printed with some long javascript.

(I suppose there can be some standard mechanism to emulate rendering as real browser page... but probably too complicated. Can understand if too much work for any possible javascript and impossible to fix universally...  but wanted to give feedback.)

Regards!

**Required info:**
 - Urls
series: https://www.novelupdates.com/series/i-became-a-flashing-genius-at-the-magic-academy/?pg=1&grp=26442
(i.e. chapters filtered to specific translator iNoveltranslation )
single chapter: https://inoveltranslation.com/chapters/3489

 - Browser: Firefox v113.0.1, Linux

 - Extension Version: not sure but probably the latest

**Comment by maoserr** [comment]
javascript apps type websites will not be supported by the toc parser. I'm working on an interactive chap parser, but it's not ready yet.

**Comment by pkartsev** [comment]
Yes, thanks!

**Comment by maoserr** [comment]
I release the interactive chap parser, it should show up in the app stores soon.
