### ISSUE TITLE
[BUG] Webnovel

### ISSUE THREAD

**Issue by zeoint** [maoserr/epublifier#159]
**Describe the bug**
Not loading novels from [webnovel](https://www.webnovel.com).

**Required info (please complete the following information):**
 - [Url - God's eyes](https://www.webnovel.com/book/god%C2%B4s-eyes_18912903106700005)
 - Browser [Firefox]
 - Extension Version [2.0.56]

**Comment by maoserr** [comment]
are you doing toc parsing or chap parsing?

**Comment by maoserr** [comment]
Looks like chap parser works, just there's no next chap button, instead it looks like using right arrow key advances chap. I'll add a keyboard chap advancement option

**Comment by maoserr** [comment]
hmm, looks like they have put in some countermeasures against scraping, I'll leave this open, but I don't think I'll have time to solve this one in the near future

**Comment by maoserr** [comment]
Closing this as won't fix. May revisit in the future.
