### ISSUE TITLE
[BUG] shift + click for range is not working

### ISSUE THREAD

**Issue by samanta-widjaja** [maoserr/epublifier#172]
**Describe the bug**
Shift + click to select range is not working. 
Clicking each chapter is buggy, after clicking a few sometimes when clicking new chapter the previous selected become unselected

**Required info (please complete the following information):**
 - Url https://www.novelupdates.com/series/trash-of-the-counts-family/
 - Browser chrome, firefox
 - Extension Version 2.0.56

**Comment by maoserr** [comment]
hmmm, I'm not really understanding, shift click is only for selecting ranges. Do you mean ctrl click?

**Comment by samanta-widjaja** [comment]
I want to select range, such as chapter 1 until 100. I use shift + click and select chapter 1 and 100, but chapter 2 - 99 is not selected. 

When I tried to click individually chapter 1 - 100, sometimes, for example after chapter 1 - 6 already selected, after I click chapter 7. Chapter 1 - 6 reseted back  to unselected

**Comment by maoserr** [comment]
fixed in new version
