### ISSUE TITLE
Compatibility with kiwi browser for android

### ISSUE THREAD

**Issue by AlbahrawyTiger** [maoserr/epublifier#174]
It works in [kiwi browser](https://github.com/kiwibrowser/src.next) but it is not compatible as the buttons overlap
Also, the options extension does not open at all, and I do not know what options are available
But in general I succeeded in saving more than one epub file

**Comment by maoserr** [comment]
not sure what your ask is, I don't officially support any mobile browsers right now. If you want to make a feature request, I can put it in the todo list

**Comment by maoserr** [comment]
I tested the new version on kiwi and everything works functionality wise. Just need to add draggable events for the popup
