### ISSUE TITLE
[BUG] No Chapters Showing

### ISSUE THREAD

**Issue by SirGryphin** [maoserr/epublifier#176]
No Chapters loading on novelupdates.

 - Url: https://www.novelupdates.com/series/max-level-newbie/
 - Browser: Chrome Version 115.0.5790.110
 - Extension Version: 2.0.56

**Comment by maoserr** [comment]
works for me, did you click the hamburger button to expand all chapters first?

**Comment by SirGryphin** [comment]
@maoserr Didn't know you had to expand chapters first. Working now thank you.
