### ISSUE TITLE
Generate the html filenames to have the exact same format as the parsed Chapter Numbers (and Titles)

### ISSUE THREAD

**Issue by bonnetchuu** [maoserr/epublifier#181]
Hello!!! I just stumbled on your really amazing extension and think it works amazing!! The UI is also really really good and simple to use (especially the parser feature)!

But, if I may make a couple suggestions, would it be possible to make **each individual html filename exactly the same as the chapter number and titles that it parsed**? Just like the **extension WebToEpub**?

For example, if the chapter that was parsed became: Chapter 3 - This is a new chapter

Then the html filename in the generated epub wouldn't be "page-3.html", but it would generate as "**Chapter-3_-_This-is-a-new-chapter.html**".

This would be much more organised and easy to know which chapter is which because many translators split their chapters into parts and it's hard to match it up when each html file is numbered as a new page :D I hope this reaches you well and thank you very much for this amazing tool!!

P.S. So it's not confusing, I'll also open the second suggestion in a separate blank issue ahah. Thank you!!

**Comment by maoserr** [comment]
you mean like the internal epub filename? I mean I can do that as a low priority item, I don't think many people would be editing the epub files or dissecting it

**Comment by bonnetchuu** [comment]
Ah yes, like the filenames of each xhtml file within the epub itself :) It'd be really amazing if you could incorporate this into your extension (as low priority is fine too! I'll keep updated with the repository)! Like this image:

![image](https://github.com/maoserr/epublifier/assets/141732398/12b84b1a-47bf-4af2-a30d-378690b08820)

I'm not too certain if others like editing epubs ahah, but I've always been editing epubs before reading any :D hopefully this isn't too much of an inconvenience~ Thank you very much!!!

**Comment by maoserr** [comment]
fixed in the new version
