### ISSUE TITLE
Be able to bulk edit all chapters simultaneously rather than individually edit each chapter one by one

### ISSUE THREAD

**Issue by bonnetchuu** [maoserr/epublifier#182]
Hello again! Just for my second suggestion, I was wondering if it were possible to make a feature where the user can **bulk edit ALL chapters all at once** after they've been **properly parsed**, rather than manually clicking each chapter to edit one by one. This is because some novels have the source name attached to every chapter title so it would be easier to bulk remove them if there was a mass edit function. Perhaps this feature could be placed right **before the "Parser" tab** :) Like in the marked image below~

![image](https://github.com/maoserr/epublifier/assets/141732398/a7306be0-ebfe-4518-a792-df260846c30b)

By this, I'm also making reference to the Webtoepub extension, where there's an "Edit Chapter URLs" button that opens up to the page where **all the links and chapter titles can be mass edited together at the same time**. Please refer to the following image:

![image](https://github.com/maoserr/epublifier/assets/141732398/98cdbf51-5adc-477d-bfd5-4350cfa34c3f)

Ah and the reason I was hoping this could be implemented in your extension is although Webtoepub is good, it does not support Novelupdates (nor does any other program until I saw your amazing tool ahah). Hoping this suggestion also reaches your notice! Thank you very much!!!! :D

**Comment by maoserr** [comment]
huh, ok, that's not hard to do, but the editor was just an afterthought for me. I'm actually in the middle of splitting out the parsing/editing parts of the ui into a separate window so I can just compile epubs with one click. I'll add this to the editor.

**Comment by bonnetchuu** [comment]
OH okay! That's really good too, more convenient! I hope to see it in a new update! Thank you very much!! :D

**Comment by maoserr** [comment]
there's now import/export csv, which will allow you to bulk edit titles and urls.
