### ISSUE TITLE
password protected pages

### ISSUE THREAD

**Issue by mnioq** [maoserr/epublifier#19]
hello~ thank you for this amazing tool. i was wondering how to extract pages that are password protected (only password, no login) 
for ex this https://chrysanthemumgarden.com website requires a pw to be inserted for every chapter. see https://chrysanthemumgarden.com/novel-tl/ilf/ilf-38-2/ 
ps. i already have the password i just need to input it

**Comment by maoserr** [comment]
Hi, you would have to write your own javascript chapter parser for custom logic.
