### ISSUE TITLE
[BUG] Parses/pulls from wrong window

### ISSUE THREAD

**Issue by nivensd** [maoserr/epublifier#193]
**Describe the bug**
I have multiple windows open and when attempting to run the plugin, it attempts to pull data from another window (for example my gmail). Closing that window only makes it switch to yet another *different* window but not the window I'm opening/accessing the plugin from. Trying to limit it to only allow access to NovelUpdates and Volare (the novel host site) throws a host permissions error.

**Required info (please complete the following information):**
 - [NovelUpdates History's Strongest Senior Brother](https://www.novelupdates.com/series/historys-strongest-senior-brother)
 - Firefox 117.0.1
 - Extension Version 2.0.56

**Comment by maoserr** [comment]
hmm, it currently just pulls from the first tab it finds.  This is already address for the next version.
