### ISSUE TITLE
[BUG] Novelupdate now has no filter to expand chapter

### ISSUE THREAD

**Issue by samanta-widjaja** [maoserr/epublifier#197]
**Describe the bug**
Novelupdate now has no filter to expand chapter. They only have group filter. so i can't download multiple chapter

**Required info (please complete the following information):**
 - https://www.novelupdates.com/series/isekai-yururi-kikou-raising-children-while-being-an-adventurer/
 - https://www.novelupdates.com/series/using-the-faulty-skill-escape-i-strive-to-become-the-strongest-one-starting-from-the-utmost-low-end-of-ability-levels/
 - Chrome 117.0.5938.92, Firefox 117
 - Extension Version 2.0.56

**Comment by maoserr** [comment]
I see that they changed the behavior of the site so you that you have to login. If you login then the button re-apppears. This is not a bug.
