### ISSUE TITLE
{BUG] New bug: https://www.novelupdates.com

### ISSUE THREAD

**Issue by S1nglish** [maoserr/epublifier#309]
**Describe the bug**

**Required info (please complete the following information):**
 - Url: https://www.novelupdates.com
 - Browser: Firefox
 - Extension Version: 3.0.125
Unable to generate green button for chapter list on chrome and not showing the chapters on FireFox from novel updates.  if possible I love this extension can you fix either or, or send a step by step manual with pictures of how to work the extenion so i can test it out once more and report the issue I am facing to greater detail[

**Comment by maoserr** [comment]
the url you have listed is not a specific series url, so the tool won't work.
