### ISSUE TITLE
[BUG] Unable to Parse Chapters

### ISSUE THREAD

**Issue by odfu** [maoserr/epublifier#343]
**Describe the bug**
Whenever I try to parse the chapters via NovelUpdates, I keep getting an 'out is null' result. Copying the chapter links directly into the parser also yields the same results.

**Required info (please complete the following information):**
 - Url: https://www.novelupdates.com/series/circumstances-of-a-fallen-lord/comment-page-2/?pg=2#myTable
 - Browser: Firefox
 - Extension Version: v3.0.125

**Comment by maoserr** [comment]
Novelupdate won't parse for me, but the TOC page works fine.

Anyways, I'm not able to reproduce your issue

**Comment by odfu** [comment]
This is what I see when I try to parse from Novelupdates. For the TOC page, are you talking about the TOC page on Foxaholic?

![Screenshot 2024-04-24 233745](https://github.com/maoserr/epublifier/assets/167141676/d001031b-e755-492e-b869-009cf1999141)
![Screenshot 2024-04-24 234510](https://github.com/maoserr/epublifier/assets/167141676/17bd7103-ab05-4c03-9eb3-cc7b9c80a04f)

**Comment by maoserr** [comment]
Still not able to re-produce, but anyways, it won't work on novel updates.

Right, you need to go to foxholic TOC page and set the following in the links regex, and click reparse link:

![image](https://github.com/maoserr/epublifier/assets/148564/9a17268e-d277-40e1-9b01-3f78530df242)

**Comment by odfu** [comment]
Thank you for all your help
