### ISSUE TITLE
[BUG] New bug: https://www.novelupdates.com

### ISSUE THREAD

**Issue by charleslita** [maoserr/epublifier#361]
**Describe the bug**
Data Base Connection Issue and Access Denied pop up after parsing the chapters, cannot proceed to download. 

**Required info (please complete the following information):**
 - Url: https://www.novelupdates.com/series/saving-unpermitted/
 - Browser: Chrome
 - Extension Version: 3.0.125
![image](https://github.com/maoserr/epublifier/assets/152690629/520114ea-3888-4fa3-8809-b490a1be1e6b)
![image](https://github.com/maoserr/epublifier/assets/152690629/e3bff117-3143-435c-b01b-d89d6b41d5df)

**Comment by maoserr** [comment]
I'm not able to reproduce. I tried parsing chapter 1-30, it worked just fine on my end.

**Comment by maoserr** [comment]
closing since no response
