### ISSUE TITLE
[BUG] New bug

### ISSUE THREAD

**Issue by Jgorilla** [maoserr/epublifier#374]
**Describe the bug**
when it finishes parsing the chapters it says "out is null"
not the first time, it's been a while when i try to use it on any link it says out is null

**Required info (please complete the following information):**
 - Url [(https://www.royalroad.com/fiction/78827/healer-of-monsters)] or like [https://www.royalroad.com/fiction/68679/return-of-the-runebound-professor] 
 - Browser [firefox]
 - Extension Version [3.0.125]

**Comment by maoserr** [comment]
I'm not seeing your error. I see: 

Cannot read properties of null (reading 'title')

sometimes. Looks like a throttling issue. But I was able to parse the first 20 chapters and generate an epub after some retrys. 

This is both on firefox and chrome.

![image](https://github.com/maoserr/epublifier/assets/148564/f87359e2-e445-4f0b-b80d-814cb7734953)

**Comment by maoserr** [comment]
can you copy/paste what's in the log tab?

**Comment by Jgorilla** [comment]
its been a while since i could never make an epub from royalroad

**Comment by Jgorilla** [comment]
ok, i make a breakthrough finally, wondered why i saw other people getting the "out is null" error while you the creator never did.
tried to disable some add-ons and that didnt work then tried vpn 
a vpn to germany didnt work either but to usa worked and it worked!!
now the log is "Detected Royalroad.
Parsing links with prefix chapter (92 chapters)
Chapter 0
Chapter 1
Chapter 2
Parsing chapter content: 0
Parsing chapter content: 2
Parsing chapter content: 1
Chapter 3
Chapter 4
Chapter 5
Parsing chapter content: 3
Parsing chapter content: 4
Parsing chapter content: 5
Chapter 6
Chapter 7
Chapter 8
Parsing chapter content: 6
Parsing chapter content: 7
Parsing chapter content: 8
Chapter 9
Chapter 10
Chapter 11
Parsing chapter content: 9
Parsing chapter content: 10
Parsing chapter content: 11
Chapter 12
Chapter 13
Chapter 14
Parsing chapter content: 12
Parsing chapter content: 13
Parsing chapter content: 14
Chapter 15
Chapter 16
Chapter 17
Parsing chapter content: 15
Parsing chapter content: 16
Parsing chapter content: 17
Chapter 18
Chapter 19
Chapter 20
Parsing chapter content: 18
Parsing chapter content: 19
Parsing chapter content: 20
Chapter 21
Chapter 22
Chapter 23
Parsing chapter content: 21
Parsing chapter content: 22
Parsing chapter content: 23
Chapter 24
Chapter 25
Chapter 26
Parsing chapter content: 24
Parsing chapter content: 25
Parsing chapter content: 26
Chapter 27
Chapter 28
Chapter 29
Parsing chapter content: 27
Parsing chapter content: 28
Parsing chapter content: 29
Chapter 30
Chapter 31
Chapter 32
Parsing chapter content: 30
Parsing chapter content: 31
Parsing chapter content: 32
Chapter 33
Chapter 34
Chapter 35
Parsing chapter content: 33
Parsing chapter content: 34
Parsing chapter content: 35
Chapter 36
Chapter 37
Chapter 38
Parsing chapter content: 36
Parsing chapter content: 37
Parsing chapter content: 38
Chapter 39
Chapter 40
Parsing chapter content: 39
Parsing chapter content: 40
Chapter 41
Parsing chapter content: 41
Chapter 42
Chapter 43
Parsing chapter content: 42
Parsing chapter content: 43
Chapter 44
Parsing chapter content: 44
Chapter 45
Chapter 46
Parsing chapter content: 46
Parsing chapter content: 45
Chapter 47
Parsing chapter content: 47
Chapter 48
Chapter 49
Parsing chapter content: 49
Parsing chapter content: 48
Chapter 50
Parsing chapter content: 50
Chapter 51
Parsing chapter content: 51
Chapter 52
Chapter 53
Parsing chapter content: 52
Parsing chapter content: 53
Chapter 54
Parsing chapter content: 54
Chapter 55
Chapter 56
Parsing chapter content: 55
Parsing chapter content: 56
Chapter 57
Parsing chapter content: 57
Chapter 58
Chapter 59
Parsing chapter content: 59
Parsing chapter content: 58
Chapter 60
Parsing chapter content: 60
Chapter 61
Chapter 62
Chapter 63
Parsing chapter content: 61
Parsing chapter content: 62
Parsing chapter content: 63
Chapter 64
Chapter 65
Chapter 66
Parsing chapter content: 64
Parsing chapter content: 65
Parsing chapter content: 66
Chapter 67
Chapter 68
Chapter 69
Parsing chapter content: 67
Parsing chapter content: 69
Parsing chapter content: 68
Chapter 70
Chapter 71
Chapter 72
Parsing chapter content: 72
Parsing chapter content: 71
Parsing chapter content: 70
Chapter 73
Chapter 74
Chapter 75
Parsing chapter content: 73
Parsing chapter content: 74
Parsing chapter content: 75
Chapter 76
Chapter 77
Chapter 78
Parsing chapter content: 77
Parsing chapter content: 76
Parsing chapter content: 78
Chapter 79
Chapter 80
Chapter 81
Parsing chapter content: 79
Parsing chapter content: 81
Parsing chapter content: 80
Chapter 82
Chapter 83
Chapter 84
Parsing chapter content: 83
Parsing chapter content: 84
Parsing chapter content: 82
Chapter 85
Chapter 86
Chapter 87
Parsing chapter content: 87
Parsing chapter content: 85
Parsing chapter content: 86
Chapter 88
Chapter 89
Chapter 90
Parsing chapter content: 88
Parsing chapter content: 89
Parsing chapter content: 90
Chapter 91
Parsing chapter content: 91
Generating ePub
Zip: 0.00 %, current file = mimetype
Zip: 0.98 %, current file = mimetype
Zip: 0.98 %, current file = META-INF/
Zip: 1.96 %, current file = META-INF/container.xml
Zip: 2.94 %, current file = META-INF/container.xml
Zip: 2.94 %, current file = OEBPS/
Zip: 3.92 %, current file = OEBPS/title-page.html
Zip: 4.90 %, current file = OEBPS/title-page.html
Zip: 4.90 %, current file = OEBPS/cover-image.png
Zip: 5.26 %, current file = OEBPS/cover-image.png
Zip: 5.43 %, current file = OEBPS/cover-image.png
Zip: 5.61 %, current file = OEBPS/cover-image.png
Zip: 5.79 %, current file = OEBPS/cover-image.png
Zip: 5.88 %, current file = OEBPS/cover-image.png
Zip: 5.88 %, current file = OEBPS/cover-image.png
Zip: 5.88 %, current file = OEBPS/front-cover.html
Zip: 6.86 %, current file = OEBPS/front-cover.html
Zip: 6.86 %, current file = OEBPS/page-0-volume_5__chapter_3___healer_of_monsters.html
Zip: 7.84 %, current file = OEBPS/page-0-volume_5__chapter_3___healer_of_monsters.html
Zip: 7.84 %, current file = OEBPS/page-1-volume_5__chapter_4___healer_of_monsters.html
Zip: 8.82 %, current file = OEBPS/page-1-volume_5__chapter_4___healer_of_monsters.html
Zip: 8.82 %, current file = OEBPS/page-2-volume_5__chapter_5___healer_of_monsters.html
Zip: 9.80 %, current file = OEBPS/page-2-volume_5__chapter_5___healer_of_monsters.html
Zip: 9.80 %, current file = OEBPS/page-3-volume_5__chapter_6___healer_of_monsters.html
Zip: 10.78 %, current file = OEBPS/page-3-volume_5__chapter_6___healer_of_monsters.html
Zip: 10.78 %, current file = OEBPS/page-4-volume_5__chapter_7___healer_of_monsters.html
Zip: 11.76 %, current file = OEBPS/page-4-volume_5__chapter_7___healer_of_monsters.html
Zip: 11.76 %, current file = OEBPS/page-5-volume_5__chapter_8___healer_of_monsters.html
Zip: 12.75 %, current file = OEBPS/page-5-volume_5__chapter_8___healer_of_monsters.html
Zip: 12.75 %, current file = OEBPS/page-6-volume_5__chapter_9___healer_of_monsters.html
Zip: 13.73 %, current file = OEBPS/page-6-volume_5__chapter_9___healer_of_monsters.html
Zip: 13.73 %, current file = OEBPS/page-7-volume_5__chapter_10___healer_of_monsters.html
Zip: 14.71 %, current file = OEBPS/page-7-volume_5__chapter_10___healer_of_monsters.html
Zip: 14.71 %, current file = OEBPS/page-8-volume_5__chapter_11___healer_of_monsters.html
Zip: 15.69 %, current file = OEBPS/page-8-volume_5__chapter_11___healer_of_monsters.html
Zip: 15.69 %, current file = OEBPS/page-9-volume_5__chapter_12___healer_of_monsters.html
Zip: 16.67 %, current file = OEBPS/page-9-volume_5__chapter_12___healer_of_monsters.html
Zip: 16.67 %, current file = OEBPS/page-10-volume_5__chapter_13___healer_of_monsters.html
Zip: 17.65 %, current file = OEBPS/page-10-volume_5__chapter_13___healer_of_monsters.html
Zip: 17.65 %, current file = OEBPS/page-11-volume_5__chapter_14___healer_of_monsters.html
Zip: 18.63 %, current file = OEBPS/page-11-volume_5__chapter_14___healer_of_monsters.html
Zip: 18.63 %, current file = OEBPS/page-12-volume_5__chapter_15___healer_of_monsters.html
Zip: 19.61 %, current file = OEBPS/page-12-volume_5__chapter_15___healer_of_monsters.html
Zip: 19.61 %, current file = OEBPS/page-13-volume_5__chapter_16___healer_of_monsters.html
Zip: 20.59 %, current file = OEBPS/page-13-volume_5__chapter_16___healer_of_monsters.html
Zip: 20.59 %, current file = OEBPS/page-14-volume_5__chapter_17___healer_of_monsters.html
Zip: 21.57 %, current file = OEBPS/page-14-volume_5__chapter_17___healer_of_monsters.html
Zip: 21.57 %, current file = OEBPS/page-15-volume_5__chapter_18___healer_of_monsters.html
Zip: 22.55 %, current file = OEBPS/page-15-volume_5__chapter_18___healer_of_monsters.html
Zip: 22.55 %, current file = OEBPS/page-16-volume_5__chapter_19___healer_of_monsters.html
Zip: 23.53 %, current file = OEBPS/page-16-volume_5__chapter_19___healer_of_monsters.html
Zip: 23.53 %, current file = OEBPS/page-17-volume_5__chapter_20___healer_of_monsters.html
Zip: 24.51 %, current file = OEBPS/page-17-volume_5__chapter_20___healer_of_monsters.html
Zip: 24.51 %, current file = OEBPS/page-18-volume_5__chapter_21___healer_of_monsters.html
Zip: 25.49 %, current file = OEBPS/page-18-volume_5__chapter_21___healer_of_monsters.html
Zip: 25.49 %, current file = OEBPS/page-19-volume_5__chapter_22___healer_of_monsters.html
Zip: 26.47 %, current file = OEBPS/page-19-volume_5__chapter_22___healer_of_monsters.html
Zip: 26.47 %, current file = OEBPS/page-20-volume_5__chapter_23___healer_of_monsters.html
Zip: 27.45 %, current file = OEBPS/page-20-volume_5__chapter_23___healer_of_monsters.html
Zip: 27.45 %, current file = OEBPS/page-21-volume_5__chapter_24___healer_of_monsters.html
Zip: 28.43 %, current file = OEBPS/page-21-volume_5__chapter_24___healer_of_monsters.html
Zip: 28.43 %, current file = OEBPS/page-22-volume_6__chapter_1___healer_of_monsters.html
Zip: 29.41 %, current file = OEBPS/page-22-volume_6__chapter_1___healer_of_monsters.html
Zip: 29.41 %, current file = OEBPS/page-23-volume_6__chapter_2___healer_of_monsters.html
Zip: 30.39 %, current file = OEBPS/page-23-volume_6__chapter_2___healer_of_monsters.html
Zip: 30.39 %, current file = OEBPS/page-24-volume_6__chpater_3___healer_of_monsters.html
Zip: 31.37 %, current file = OEBPS/page-24-volume_6__chpater_3___healer_of_monsters.html
Zip: 31.37 %, current file = OEBPS/page-25-volume_6__chapter_4___healer_of_monsters.html
Zip: 32.35 %, current file = OEBPS/page-25-volume_6__chapter_4___healer_of_monsters.html
Zip: 32.35 %, current file = OEBPS/page-26-volume_6__chapter_5___healer_of_monsters.html
Zip: 33.33 %, current file = OEBPS/page-26-volume_6__chapter_5___healer_of_monsters.html
Zip: 33.33 %, current file = OEBPS/page-27-volume_6__chapter_6___healer_of_monsters.html
Zip: 34.31 %, current file = OEBPS/page-27-volume_6__chapter_6___healer_of_monsters.html
Zip: 34.31 %, current file = OEBPS/page-28-volume_6__chapter_7___healer_of_monsters.html
Zip: 35.29 %, current file = OEBPS/page-28-volume_6__chapter_7___healer_of_monsters.html
Zip: 35.29 %, current file = OEBPS/page-29-volume_6__chapter_8___healer_of_monsters.html
Zip: 36.27 %, current file = OEBPS/page-29-volume_6__chapter_8___healer_of_monsters.html
Zip: 36.27 %, current file = OEBPS/page-30-volume_6__chapter_9___healer_of_monsters.html
Zip: 37.25 %, current file = OEBPS/page-30-volume_6__chapter_9___healer_of_monsters.html
Zip: 37.25 %, current file = OEBPS/page-31-volume_6__chapter_10___healer_of_monsters.html
Zip: 38.24 %, current file = OEBPS/page-31-volume_6__chapter_10___healer_of_monsters.html
Zip: 38.24 %, current file = OEBPS/page-32-volume_6__chapter_11___healer_of_monsters.html
Zip: 39.22 %, current file = OEBPS/page-32-volume_6__chapter_11___healer_of_monsters.html
Zip: 39.22 %, current file = OEBPS/page-33-volume_6__chapter_12___healer_of_monsters.html
Zip: 40.20 %, current file = OEBPS/page-33-volume_6__chapter_12___healer_of_monsters.html
Zip: 40.20 %, current file = OEBPS/page-34-volume_6__chapter_13___healer_of_monsters.html
Zip: 41.18 %, current file = OEBPS/page-34-volume_6__chapter_13___healer_of_monsters.html
Zip: 41.18 %, current file = OEBPS/page-35-volume_6__chapter_14___healer_of_monsters.html
Zip: 42.16 %, current file = OEBPS/page-35-volume_6__chapter_14___healer_of_monsters.html
Zip: 42.16 %, current file = OEBPS/page-36-volume_6__chapter_15___healer_of_monsters.html
Zip: 43.14 %, current file = OEBPS/page-36-volume_6__chapter_15___healer_of_monsters.html
Zip: 43.14 %, current file = OEBPS/page-37-volume_6__chapter_16___healer_of_monsters.html
Zip: 44.12 %, current file = OEBPS/page-37-volume_6__chapter_16___healer_of_monsters.html
Zip: 44.12 %, current file = OEBPS/page-38-volume_6__chapter_17___healer_of_monsters.html
Zip: 45.10 %, current file = OEBPS/page-38-volume_6__chapter_17___healer_of_monsters.html
Zip: 45.10 %, current file = OEBPS/page-39-volume_6__chapter_18___healer_of_monsters.html
Zip: 46.08 %, current file = OEBPS/page-39-volume_6__chapter_18___healer_of_monsters.html
Zip: 46.08 %, current file = OEBPS/page-40-volume_6__chapter_19___healer_of_monsters.html
Zip: 47.06 %, current file = OEBPS/page-40-volume_6__chapter_19___healer_of_monsters.html
Zip: 47.06 %, current file = OEBPS/page-41-volume_6__chapter_20___healer_of_monsters.html
Zip: 48.04 %, current file = OEBPS/page-41-volume_6__chapter_20___healer_of_monsters.html
Zip: 48.04 %, current file = OEBPS/page-42-volume_6__chapter_21___healer_of_monsters.html
Zip: 49.02 %, current file = OEBPS/page-42-volume_6__chapter_21___healer_of_monsters.html
Zip: 49.02 %, current file = OEBPS/page-43-volume_6__chapter_22___healer_of_monsters.html
Zip: 50.00 %, current file = OEBPS/page-43-volume_6__chapter_22___healer_of_monsters.html
Zip: 50.00 %, current file = OEBPS/page-44-volume_6__chapter_23___healer_of_monsters.html
Zip: 50.98 %, current file = OEBPS/page-44-volume_6__chapter_23___healer_of_monsters.html
Zip: 50.98 %, current file = OEBPS/page-45-volume_6__chapter_24___healer_of_monsters.html
Zip: 51.96 %, current file = OEBPS/page-45-volume_6__chapter_24___healer_of_monsters.html
Zip: 51.96 %, current file = OEBPS/page-46-volume_7__chapter_1___healer_of_monsters.html
Zip: 52.94 %, current file = OEBPS/page-46-volume_7__chapter_1___healer_of_monsters.html
Zip: 52.94 %, current file = OEBPS/page-47-volume_7__chapter_2___healer_of_monsters.html
Zip: 53.92 %, current file = OEBPS/page-47-volume_7__chapter_2___healer_of_monsters.html
Zip: 53.92 %, current file = OEBPS/page-48-volume_7__chapter_3___healer_of_monsters.html
Zip: 54.90 %, current file = OEBPS/page-48-volume_7__chapter_3___healer_of_monsters.html
Zip: 54.90 %, current file = OEBPS/page-49-volume_7__chapter_4___healer_of_monsters.html
Zip: 55.88 %, current file = OEBPS/page-49-volume_7__chapter_4___healer_of_monsters.html
Zip: 55.88 %, current file = OEBPS/page-50-volume_7__chapter_5___healer_of_monsters.html
Zip: 56.86 %, current file = OEBPS/page-50-volume_7__chapter_5___healer_of_monsters.html
Zip: 56.86 %, current file = OEBPS/page-51-volume_7__chapter_6___healer_of_monsters.html
Zip: 57.84 %, current file = OEBPS/page-51-volume_7__chapter_6___healer_of_monsters.html
Zip: 57.84 %, current file = OEBPS/page-52-volume_7__chapter_7___healer_of_monsters.html
Zip: 58.82 %, current file = OEBPS/page-52-volume_7__chapter_7___healer_of_monsters.html
Zip: 58.82 %, current file = OEBPS/page-53-volume_7__chapter_8___healer_of_monsters.html
Zip: 59.80 %, current file = OEBPS/page-53-volume_7__chapter_8___healer_of_monsters.html
Zip: 59.80 %, current file = OEBPS/page-54-volume_7__chapter_9___healer_of_monsters.html
Zip: 60.78 %, current file = OEBPS/page-54-volume_7__chapter_9___healer_of_monsters.html
Zip: 60.78 %, current file = OEBPS/page-55-volume_7__chapter_10___healer_of_monsters.html
Zip: 61.76 %, current file = OEBPS/page-55-volume_7__chapter_10___healer_of_monsters.html
Zip: 61.76 %, current file = OEBPS/page-56-volume_7__chapter_11___healer_of_monsters.html
Zip: 62.75 %, current file = OEBPS/page-56-volume_7__chapter_11___healer_of_monsters.html
Zip: 62.75 %, current file = OEBPS/page-57-volume_7__chapter_12___healer_of_monsters.html
Zip: 63.73 %, current file = OEBPS/page-57-volume_7__chapter_12___healer_of_monsters.html
Zip: 63.73 %, current file = OEBPS/page-58-volume_7__chapter_13___healer_of_monsters.html
Zip: 64.71 %, current file = OEBPS/page-58-volume_7__chapter_13___healer_of_monsters.html
Zip: 64.71 %, current file = OEBPS/page-59-volume_7__chapter_14___healer_of_monsters.html
Zip: 65.69 %, current file = OEBPS/page-59-volume_7__chapter_14___healer_of_monsters.html
Zip: 65.69 %, current file = OEBPS/page-60-volume_7__chapter_15___healer_of_monsters.html
Zip: 66.67 %, current file = OEBPS/page-60-volume_7__chapter_15___healer_of_monsters.html
Zip: 66.67 %, current file = OEBPS/page-61-volume_7__chapter_16___healer_of_monsters.html
Zip: 67.65 %, current file = OEBPS/page-61-volume_7__chapter_16___healer_of_monsters.html
Zip: 67.65 %, current file = OEBPS/page-62-volume_7__chapter_17___healer_of_monsters.html
Zip: 68.63 %, current file = OEBPS/page-62-volume_7__chapter_17___healer_of_monsters.html
Zip: 68.63 %, current file = OEBPS/page-63-volume_7__chapter_18___healer_of_monsters.html
Zip: 69.61 %, current file = OEBPS/page-63-volume_7__chapter_18___healer_of_monsters.html
Zip: 69.61 %, current file = OEBPS/page-64-volume_7__chapter_19___healer_of_monsters.html
Zip: 70.59 %, current file = OEBPS/page-64-volume_7__chapter_19___healer_of_monsters.html
Zip: 70.59 %, current file = OEBPS/page-65-volume_7__chapter_20___healer_of_monsters.html
Zip: 71.57 %, current file = OEBPS/page-65-volume_7__chapter_20___healer_of_monsters.html
Zip: 71.57 %, current file = OEBPS/page-66-volume_7__chapter_21___healer_of_monsters.html
Zip: 72.55 %, current file = OEBPS/page-66-volume_7__chapter_21___healer_of_monsters.html
Zip: 72.55 %, current file = OEBPS/page-67-volume_7__chapter_22___healer_of_monsters.html
Zip: 73.53 %, current file = OEBPS/page-67-volume_7__chapter_22___healer_of_monsters.html
Zip: 73.53 %, current file = OEBPS/page-68-volume_7__chapter_23___healer_of_monsters.html
Zip: 74.51 %, current file = OEBPS/page-68-volume_7__chapter_23___healer_of_monsters.html
Zip: 74.51 %, current file = OEBPS/page-69-volume_8__chapter_1___healer_of_monsters.html
Zip: 75.49 %, current file = OEBPS/page-69-volume_8__chapter_1___healer_of_monsters.html
Zip: 75.49 %, current file = OEBPS/page-70-volume_8__chapter_2___healer_of_monsters.html
Zip: 76.47 %, current file = OEBPS/page-70-volume_8__chapter_2___healer_of_monsters.html
Zip: 76.47 %, current file = OEBPS/page-71-volume_8__chapter_3___healer_of_monsters.html
Zip: 77.45 %, current file = OEBPS/page-71-volume_8__chapter_3___healer_of_monsters.html
Zip: 77.45 %, current file = OEBPS/page-72-volume_8__chapter_4___healer_of_monsters.html
Zip: 78.43 %, current file = OEBPS/page-72-volume_8__chapter_4___healer_of_monsters.html
Zip: 78.43 %, current file = OEBPS/page-73-volume_8__chapter_5___healer_of_monsters.html
Zip: 79.41 %, current file = OEBPS/page-73-volume_8__chapter_5___healer_of_monsters.html
Zip: 79.41 %, current file = OEBPS/page-74-volume_8__chapter_6___healer_of_monsters.html
Zip: 80.39 %, current file = OEBPS/page-74-volume_8__chapter_6___healer_of_monsters.html
Zip: 80.39 %, current file = OEBPS/page-75-volume_8__chapter_7___healer_of_monsters.html
Zip: 81.37 %, current file = OEBPS/page-75-volume_8__chapter_7___healer_of_monsters.html
Zip: 81.37 %, current file = OEBPS/page-76-volume_8__chapter_8___healer_of_monsters.html
Zip: 82.35 %, current file = OEBPS/page-76-volume_8__chapter_8___healer_of_monsters.html
Zip: 82.35 %, current file = OEBPS/page-77-volume_8__chapter_9___healer_of_monsters.html
Zip: 83.33 %, current file = OEBPS/page-77-volume_8__chapter_9___healer_of_monsters.html
Zip: 83.33 %, current file = OEBPS/page-78-volume_8__chapter_10___healer_of_monsters.html
Zip: 84.31 %, current file = OEBPS/page-78-volume_8__chapter_10___healer_of_monsters.html
Zip: 84.31 %, current file = OEBPS/page-79-volume_8__chapter_11___healer_of_monsters.html
Zip: 85.29 %, current file = OEBPS/page-79-volume_8__chapter_11___healer_of_monsters.html
Zip: 85.29 %, current file = OEBPS/page-80-volume_8__chapter_12___healer_of_monsters.html
Zip: 86.27 %, current file = OEBPS/page-80-volume_8__chapter_12___healer_of_monsters.html
Zip: 86.27 %, current file = OEBPS/page-81-volume_8__chapter_13___healer_of_monsters.html
Zip: 87.25 %, current file = OEBPS/page-81-volume_8__chapter_13___healer_of_monsters.html
Zip: 87.25 %, current file = OEBPS/page-82-volume_8__chapter_14___healer_of_monsters.html
Zip: 88.24 %, current file = OEBPS/page-82-volume_8__chapter_14___healer_of_monsters.html
Zip: 88.24 %, current file = OEBPS/page-83-volume_8__chapter_15___healer_of_monsters.html
Zip: 89.22 %, current file = OEBPS/page-83-volume_8__chapter_15___healer_of_monsters.html
Zip: 89.22 %, current file = OEBPS/page-84-volume_8__chapter_16___healer_of_monsters.html
Zip: 90.20 %, current file = OEBPS/page-84-volume_8__chapter_16___healer_of_monsters.html
Zip: 90.20 %, current file = OEBPS/page-85-volume_8__chapter_17___healer_of_monsters.html
Zip: 91.18 %, current file = OEBPS/page-85-volume_8__chapter_17___healer_of_monsters.html
Zip: 91.18 %, current file = OEBPS/page-86-volume_8__chapter_18___healer_of_monsters.html
Zip: 92.16 %, current file = OEBPS/page-86-volume_8__chapter_18___healer_of_monsters.html
Zip: 92.16 %, current file = OEBPS/page-87-volume_8__chapter_19___healer_of_monsters.html
Zip: 93.14 %, current file = OEBPS/page-87-volume_8__chapter_19___healer_of_monsters.html
Zip: 93.14 %, current file = OEBPS/page-88-volume_8__chapter_20___healer_of_monsters.html
Zip: 94.12 %, current file = OEBPS/page-88-volume_8__chapter_20___healer_of_monsters.html
Zip: 94.12 %, current file = OEBPS/page-89-volume_8__chapter_21___healer_of_monsters.html
Zip: 95.10 %, current file = OEBPS/page-89-volume_8__chapter_21___healer_of_monsters.html
Zip: 95.10 %, current file = OEBPS/page-90-volume_8__chapter_22___healer_of_monsters.html
Zip: 96.08 %, current file = OEBPS/page-90-volume_8__chapter_22___healer_of_monsters.html
Zip: 96.08 %, current file = OEBPS/page-90-volume_8__chapter_22___healer_of_monsters.html
Zip: 96.08 %, current file = OEBPS/page-91-volume_8__chapter_23___healer_of_monsters.html
Zip: 97.06 %, current file = OEBPS/page-91-volume_8__chapter_23___healer_of_monsters.html
Zip: 97.06 %, current file = book.opf
Zip: 98.04 %, current file = book.opf
Zip: 98.04 %, current file = OEBPS/table-of-contents.html
Zip: 99.02 %, current file = OEBPS/table-of-contents.html
Zip: 99.02 %, current file = toc.ncx
Zip: 100.00 %, current file = toc.ncx
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %
Zip: 100.00 %"

**Comment by Jgorilla** [comment]
dunno if you can do something about it but thank you for your time man
your work is a life saver T-T

**Comment by maoserr** [comment]
maybe there's some additional verification if you're not in the US. I'm not going to be able to reproduce that kind of issue since I'm in US. I'll leave this open for now in case someone can provide more info.

**Comment by Jgorilla** [comment]
thanks anyway, and if you want you can try it with a vpn like windscribe (free and powerful)

**Comment by Mepper65** [comment]
I started getting the "out is null" error in the last few days.  It has probably been at least a month since I last used the extension so I'm not sure when the the problem started.  I had seen the problem in the past but after a while the problem disappeared so I figured it had been fixed, but now it seems to be back...
Browser: Firefox v129.0.2
Epubifier v3.0.136
URL: https://www.novelupdates.com/series/became-a-medieval-fantasy-wizard/
I tried a different book on the same website and the extension worked properly, so there is probably something strange with this particular page.

**Comment by maoserr** [comment]
that link is not a web page, it's an app, you'll have to parse it as an app. This setting works fine for me:

![image](https://github.com/user-attachments/assets/9bd7f574-529e-499d-978c-30b81583237e)

**Comment by maoserr** [comment]
That's not a page, but an app,

this setting worked fine: 
![image](https://github.com/user-attachments/assets/2a3bde72-0fb6-4c34-9a97-70760b00355a)

**Comment by Maeril** [comment]
Hi there, 

I've been having the exact same issue on novelupdates. I am in France and the error persists no matter what I do. 

![Screenshot from 2024-09-02 22-22-13](https://github.com/user-attachments/assets/c337130a-1afe-44ac-beb7-57ab3906bbcd)

Parsing as pages doesn't work. 
Parsing as an app doesn't work.
Hell, I even tried to switch to Firefox, to no avail.
I also tried the VPN trick . No luck.
 
Please please please can you look into it? 
Because of this, I can't use your app at all right now :(

Thank you!

**Comment by Jgorilla** [comment]
If using windscribe VPN doesn't work then do the same as me and switch to
WebToEpub add-on

**Comment by maoserr** [comment]
> Hi there,
> 
> I've been having the exact same issue on novelupdates. I am in France and the error persists no matter what I do.
> 
> ![Screenshot from 2024-09-02 22-22-13](https://private-user-images.githubusercontent.com/40640880/363786641-c337130a-1afe-44ac-beb7-57ab3906bbcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTYyNDQsIm5iZiI6MTcyNTMxNTk0NCwicGF0aCI6Ii80MDY0MDg4MC8zNjM3ODY2NDEtYzMzNzEzMGEtMWFmZS00NGFjLWJlYjctNTdhYjM5MDZiYmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDIyMjU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NzJjOGJiY2U5OGFkMjZkZDVmMTljNWRlN2FiYTI1NjlmMGVmMDNjYTM0YzM4NjY1ZjJjNzVhZTc1ZTcxYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V53eGWa5nxJ_ZVmYmlVj9V2_kgy1SiR6otepWQxe34Q)
> 
> Parsing as pages doesn't work. Parsing as an app doesn't work. Hell, I even tried to switch to Firefox, to no avail. I also tried the VPN trick . No luck.
> 
> Please please please can you look into it? Because of this, I can't use your app at all right now :(
> 
> Thank you!

Can you open up a separate bug with url and brower info? thanks.
