### ISSUE TITLE
[BUG] New bug

### ISSUE THREAD

**Issue by tknx** [maoserr/epublifier#386]
**Describe the bug**
Tried to convert two different filtered translations of SSS-Class Suicide Hunter but just got images.

**Required info (please complete the following information):**
 - Url [e.g. specific series link]: https://www.novelupdates.com/series/sss-class-suicide-hunter/?pg=1&grp=72020
 - Browser [e.g. chrome, firefox]: Firefox
 - Extension Version [e.g. 2.0.24]: 3.0.136

**Comment by maoserr** [comment]
that's not a static webpage, you'll have to parse it as an app. I was able to parse the last 5 chapters fine with these settings:

![image](https://github.com/user-attachments/assets/71b137cb-ecf3-4452-a9ce-d8d722f2a6d4)
