### ISSUE TITLE
[BUG] Alternative text on images is lost  during EPUBfication

### ISSUE THREAD

**Issue by samimaat** [maoserr/epublifier#395]
First of all thanks for the tool! It's really interesting. I found a bug which after fixed would enhance the accessibility of the tool further.

**Describe the bug**
After running the tool on a website, the alternative text in images is emptied.

**Required info (please complete the following information):**
I'm running Firefox 131.0.3 and Epublifier 3.0.142.

I tried it on [Pluralistic's Retiring the US debt would retire the US dollar](https://pluralistic.net/2024/10/21/we-can-have-nice-things/#public-funds-not-taxpayer-dollars) and they write alt texts for their images.

Example of the 'cover image' and its mark up (in particular the `alt` attribute):
```html
<img 
data-recalc-dims="1" 
decoding="async" 
alt="A 19th century Puck editorial cartoon of Uncle Sam standing between two funhouse mirrors, one of which depicts him as an emaciated, terrified figure; the other depicts him as a fat and happy fellow. The background is a highly magnified US $100 bill. Over the 'fat' mirror the text from US banknotes: 'This note is legal tender for all debts private and public.'" 
src="https://i0.wp.com/craphound.com/images/pj-mmt.jpg?w=840&amp;ssl=1" 
title="" 
style="">
```

The result mark up:
```html
<img src="assets/1.jpg" alt="" />
```

I think a good solution is to check if the alt text exists and carry it over. If the `alt` attribute doesn't exist, (personally) I wouldn't 'fix' it by making it empty. This way people using a screen reader would still notice that an image is present and use whatever tools they want to get a description of it.

**Comment by maoserr** [comment]
Yea, this is no big deal, but it's going to be a change on the tsepub repo first.

**Comment by maoserr** [comment]
This bug is fixed for all images except cover images. Cover images are stored as bytes since I allow pasting directly from clipboard. It should be decoration anyways.

I'll close this issue after the extension publishes
