### ISSUE TITLE
[BUG] Only getting chapter titles within chapters

### ISSUE THREAD

**Issue by lalalasupa0** [maoserr/epublifier#398]
**Describe the bug**
This problem has only happened to me with the Genesis Studio group, I have tried the "App" parse and a few other things but I keep getting the epub that way, and idk how to set it up in the first place so I didn't do much anyway, I just hope it's repicable
[The epub I'm getting](https://www.mediafire.com/file/g9dqw4qhngot635/omniscient_first_person_s_viewpoint+(1).epub/file)

**Required info:**
 - Url: https://www.novelupdates.com/series/omniscient-first-persons-viewpoint/ https://www.novelupdates.com/series/the-main-heroines-are-trying-to-kill-me/
 - Browser: chrome / android kiwi browser and in **firefox (pc)**
 - Extension Version: android kiwi browser 124.0.6327.4, **firefox pc 131.0.3**
   * I mention Kiwi aswell bc the chrome extension has been working for me like on pc completely fine until now, Ik there's no support for mobile, is just to let you know

**Comment by maoserr** [comment]
These settings work for me for parsing the main text, but not chapter titles. If you want chapter titles, you'll have to manually create it and import it as a csv. I also noticed this site has put in some anti-scraping measures in place, so I won't be able to make this site work easily.

![image](https://github.com/user-attachments/assets/323fa2f7-e8fa-479c-b586-7ed28e5a1ca4)

**Comment by lalalasupa0** [comment]
> These settings work for me for parsing the main text, but not chapter titles. If you want chapter titles, you'll have to manually create it and import it as a csv. I also noticed this site has put in some anti-scraping measures in place, so I won't be able to make this site work easily.
> 
> Also start from this page and use "Add page": https://genesistudio.com/viewer/1880
> 
> ![image](https://private-user-images.githubusercontent.com/148564/382289162-323fa2f7-e8fa-479c-b586-7ed28e5a1ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MDMyOTgsIm5iZiI6MTczMDUwMjk5OCwicGF0aCI6Ii8xNDg1NjQvMzgyMjg5MTYyLTMyM2ZhMmY3LWU4ZmEtNDc5Yy1iNTg2LTdlZDI4ZTVhMWNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQyMzE2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmRjY2RkMGIyN2FmZTRmYTgyMzdmOTU2N2E2YjNkZDQ0NDI1YjM1YmYwNmI5ZTMxZDZlYWU2ZWQwMzFjMzJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.M0uS-0yRSuiQ4Es4xTvUkSG1tx6Oye5UQGykAtCt_QM)

Weird, I'm still getting the [epub](https://www.mediafire.com/file/fvi0rfoegjz5b8d/the_main_heroines_are_trying_to_kill_me_chs_01_368.epub/file) like before
What I did was to set it up exactly as it appears in your cc and tap "+" to add chapters, I guess that's how it should be done.
Then parse selected links and finally create epub
Maybe there's something else
After trying the parse selected links again I got `out is null` so I just stopped it there

**Comment by maoserr** [comment]
parse selectes is not needed when doing app parsing. you'll just overwrite the results.

**Comment by lalalasupa0** [comment]
> parse selectes is not needed when doing app parsing. you'll just overwrite the results.

I see, I'll try again, I'm guessing the Create Epub icon is available just like that this way
_I though it only appeared after the parse selected thing_

**Comment by maoserr** [comment]
you're not the first to get confused. but this is meant as a power user tool, so I hesistate to make it simpler.

**Comment by lalalasupa0** [comment]
Something that just came to my mind and I want to clarify, does the "Next Selector" slot always have to have something in it like `.rounded-r-full`, or is it that it always has to be put in when using parse app or instead is it something different for different websites other than this one?

And, something else, in [this web](https://penguin-squad.com/story/i-killed-the-player-of-the-academy), where I suppose the parse app thing must also be used, do I have to enter the first chapter before executing the extension? I wonder because the index ("toc") of that web is small, Idk maybe it's a special case

I really appreciate the help 🙌🙌

**Comment by maoserr** [comment]
hmm, I'll update the documentation.

**Comment by lalalasupa0** [comment]
> hmm, I'll update the documentation.

Oh damn I forgot that existed... Imma check it out

**Comment by maoserr** [comment]
> > If you want chapter titles, you'll have to manually create it and import it as a csv.
> 
> I wonder how, I can't tell 😓
> 
> ~Something that just came to my mind and I want to clarify, does the "Next Selector" slot always have to have something in it like `.rounded-r-full`, or is it that it always has to be put in when using parse app or instead is it something different for different websites other than this one?~
> 
> And, something else, in [this web](https://penguin-squad.com/story/i-killed-the-player-of-the-academy), where I suppose the parse app thing must also be used, do I have to enter the first chapter before executing the extension? I wonder because the index ("toc") of that web is small, Idk maybe it's a special case
> 
> I really appreciate the help 🙌🙌

I've updated the documentation under "Custom Webapp" parsing to answer these questions.

**Comment by lalalasupa0** [comment]
> > > If you want chapter titles, you'll have to manually create it and import it as a csv.
> > 
> > 
> > I wonder how, I can't tell 😓
> > ~Something that just came to my mind and I want to clarify, does the "Next Selector" slot always have to have something in it like `.rounded-r-full`, or is it that it always has to be put in when using parse app or instead is it something different for different websites other than this one?~
> > And, something else, in [this web](https://penguin-squad.com/story/i-killed-the-player-of-the-academy), where I suppose the parse app thing must also be used, do I have to enter the first chapter before executing the extension? I wonder because the index ("toc") of that web is small, Idk maybe it's a special case
> > I really appreciate the help 🙌🙌
> 
> I've updated the documentation under "Custom Webapp" parsing to answer these questions.

Tysm, for last...

> - Click the search button next the Next Element textbox, and select the next button, it should highlight red
> - Click the search button next to the Title Element textbox, and select the title text, or leave it blank and have the parser try to auto detect

How do I do that? I tried googling it but I couldn't find exactly how to do so.... When I click on the search icon the screen goes dark, and even if I get to "Next" with the tab key, I don't know how to select it 🤔
