### ISSUE TITLE
[BUG] Not getting chapter number and skipping a chapter in parse via Novel Updates

### ISSUE THREAD

**Issue by lalalasupa0** [maoserr/epublifier#400]
**Describe the bug**
In the novel at the url below, I am not getting the numbers of chapters 219-223, only their titles, and thus resulting off order in the list of chapters. On the group's website they are numbered, and on NU as well, of course
![Captura de pantalla 2024-11-03 041623](https://github.com/user-attachments/assets/14dd90f6-74a4-41c0-b0bb-c9b35c530c9a)
On the other hand, the parse also skipped a chapter, the 223rd

**Required info (please complete the following information):**
 - Url https://www.novelupdates.com/series/i-killed-the-player-of-the-academy/
 - Browser Brave v1.71.121 Chromium: 130.0.6723.91
 - Extension Version 3.0.150

**Comment by maoserr** [comment]
I'm not able to reproduce. getting chapter 219. If a parse fails, you have to try again sometimes because sometimes website are busy or rejects a request if it happens too fast.
![image](https://github.com/user-attachments/assets/2ebb0543-f0d6-471d-b72e-08b46fc60ee0)

**Comment by lalalasupa0** [comment]
> I'm not able to reproduce. getting chapter 219. If a parse fails, you have to try again sometimes because sometimes website are busy or rejects a request if it happens too fast. ![image](https://private-user-images.githubusercontent.com/148564/382581485-2ebb0543-f0d6-471d-b72e-08b46fc60ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODM0ODEsIm5iZiI6MTczMDY4MzE4MSwicGF0aCI6Ii8xNDg1NjQvMzgyNTgxNDg1LTJlYmIwNTQzLWYwZDYtNDcxZC1iNzJlLTA4YjQ2ZmM2MGVlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwMTE5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjQ4NDMwZjIzZGMxY2MxNDZlZTBlNGUzNmQ4MTA4ZTNkMmUyMTMxYTFjNjQwYjJkYTM1YzBmOTZkMjg0ZWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D8LuoxmAQW-lfttem79IjG14txmA7v_GcCNetk1Hy0g)

> I'm not able to reproduce. 

You did get the ch. `War for Korin, their Son-In-Law` without ch. _number_ tho

But then I guess I just need to keep trying until I get them right...
Alr I hope I do haha, ty
