### ISSUE TITLE
[Suggestion] detail optimization

### ISSUE THREAD

**Issue by xjmwx4** [maoserr/epublifier#403]
Image attachment names suggest to be composed of 11-digit random alphanumerics, and chapter html file names can be preferably adjusted as well, instead of the current ones similar to page-0-______________________x_______.html

**Comment by maoserr** [comment]
what's the problem with the existing names?

**Comment by xjmwx4** [comment]
There is no problem for epub ebook reading.

I'm tyring to converting a series of web content into an ePub eBook. Although there are existing web or tools that facilitate the merging of content into an eBook, adjustments to the underlying files are often necessary to address specific details. When adjusting, I hope I can put the images in one folder. Currently, there's an issue with duplicate image names within the project. If the image names are changed, it's also necessary to update the corresponding references within the HTML files, which can be cumbersome.

For the html file name, it was wrong in the previous issue metioned, different language appears as "____". To manually adjust these details, I would need to modify the corresponding HTML file names to ensure proper display and functionality.

**Comment by maoserr** [comment]
Can you give an example?

**Comment by xjmwx4** [comment]
> Can you give an example?

https://liqi.io/chengbao45/

**Comment by maoserr** [comment]
hmm, ok, I see the chinese characters are not being handled correctly in the chapter html

**Comment by maoserr** [comment]
This is fixed in the next version.
