### ISSUE TITLE
Gets stuck at Chapter 34

### ISSUE THREAD

**Issue by tknx** [maoserr/epublifier#68]
Tried to do this one: https://www.novelupdates.com/series/tomorrow-i-will-die-you-will-revive/

And it ends up freezing right at chapter 34.

**Comment by maoserr** [comment]
it works for me, but the chapter "[v3...](https://www.novelupdates.com/extnu/400942/)" is not parseable so I had to delete it before compiling

**Comment by tknx** [comment]
Hmm. Do you know what is rendering it unparsable? Any way to edit v3 to fix it? Obviously a book missing a chapter is a bit less useful.

**Comment by maoserr** [comment]
I looked at the chapter: https://hellping.org/bokushinu-v3/
It doesn't have any text, just a couple of images. So it won't get recognized as a chapter because the content is too short
