### ISSUE TITLE
No Chapters in Chrome

### ISSUE THREAD

**Issue by perrinaz** [maoserr/epublifier#98]
So, Firefox wouldn't allow me to install v1.2 no matter what settings I changed so I switched to trying chrome -- the lastest version in the Chrome Store.  Same Link (https://www.novelupdates.com/series/slave-harem-in-the-labyrinth-of-the-other-world-ln).  When I click "Load Chapter List" the page is blank of all information except the Title: Epublifer.  The Popup before showed the series and cover and said (as of this posting) 467 chapters detected.  It's like, somehow, the information from the popup isn't being passed to the new tab.

**Comment by maoserr** [comment]
interesting, there's a 0.5 second delay before the popup passed the data to the new tab, maybe your computer's too slow to load the new tab?

**Comment by maoserr** [comment]
I'm changing the way message passing works in the next version, not sure when it'll be ready though

**Comment by maoserr** [comment]
closing this since I changed the message passing system completely
